name: AutoFarm
main: com.github.neapovil.autofarm.AutoFarm
version: 1.0.0
api-version: 1.13
author: Neapovil
website: https://github.com/neapovil/autofarm
depend:
  - CommandAPI
permissions:
  autofarm.command.user:
    default: true
